#!/bin/bash

countryName="Canada"
countryLevel="1"
startDate="2022-02-01"

touch "Starting epinow run.txt"
# Since sometimes the script will run past midnight, we need to save the
# start date for use in the filenames
dateStub=`date +%C%y%m%d`
nice Rscript -e "countryName <- \"$countryName\"" -e "countryLevel <- \"$countryLevel\"" -e "startDate <- \"$startDate\"" -e "source(\"epinow2-regional-covidregionaldata.R\")"
touch "Ended epinow run.txt"


# copy output to upload target
cp output/summary-$dataStub/*.csv docs/epinow

# delete summary images (not used)
#rm output/summary-$dateStub/*.png

# upload process
